const Data = [
  {
    name: 'Kavisha Patel',
    roles: 'Events Convener',
    url: 'https://picsum.photos/500',
    team: 'convener',
    email: 'krpatel728@gmail.com',
    linkedin: 'https://www.linkedin.com/in/kavishapatel28072000',
    insta: 'https://www.instagram.com/kavisha_patel28/',
  },
  {
    name: 'Akash Bhat',
    roles: 'Events Convener',
    url: 'https://picsum.photos/500',
    team: 'convener',
    email: 'akashbhat0007@gmail.com',
    linkedin: 'https://www.linkedin.com/in/akash-bhat-5a234a163',
    insta: 'https://instagram.com/akash_bhat25?utm_medium=copy_link',
  },
  {
    name: 'Muskan Biala',
    roles: 'Marketing Convener',
    url: 'https://picsum.photos/500',
    team: 'convener',
    email: 'muskan.biala@gmail.com',
    linkedin: 'https://www.linkedin.com/in/muskan-biala-25898817a',
    insta: 'https://instagram.com/muskanbiala',
  },
  {
    name: 'Jinay Shah',
    roles: 'Campaigning Convener',
    url: 'https://picsum.photos/500',
    team: 'convener',
    email: 'jinayshah192@gmail.com ',
    linkedin: 'https://www.linkedin.com/in/jinay-shah-b7790518b',
    insta: 'https://instagram.com/15jinay?utm_medium=copy_link',
  },
  {
    name: 'Shivani Pandey',
    roles: 'Campaigning Convener',
    url: 'https://picsum.photos/500',
    team: 'convener',
    email: 'pandeyshivania@gmail.com',
    linkedin: 'https://www.linkedin.com/in/shivani-anand-pandey-59829a177',
    insta: 'https://www.instagram.com/she_as_vani',
  },
  {
    name: 'Utsav Doshi',
    roles: 'Events Convener',
    url: 'https://picsum.photos/500',
    team: 'convener',
    email: 'utsavdoshi321@gmail.com',
    linkedin: 'https://www.linkedin.com/in/utsav-doshi-058495196',
    insta: 'https://instagram.com/utsavdoshi_321?utm_medium=copy_link',
  },
  {
    name: 'Navneet Dubey',
    roles: 'Marketing Convener',
    url: 'https://picsum.photos/500',
    team: 'convener',
    email: 'navneetnkd123@gmail.com',
    linkedin: 'https://www.linkedin.com/in/navneet-dubey',
    insta: 'https://www.instagram.com/new_n_neat',
  },
  {
    name: 'Shubham Dave',
    roles: 'Campaigning Conevenr',
    url: 'https://picsum.photos/500',
    team: 'convener',
    email: 'daveshubham600@gmail.com',
    linkedin: 'https://www.linkedin.com/in/shubham-dave-b39494196',
    insta: 'https://instagram.com/dave_shubham_18?utm_medium=copy_link',
  },
  {
    name: 'Manashi Pandey',
    roles: 'Campaigning Convener',
    url: 'https://picsum.photos/500',
    team: 'convener',
    email: 'pandeymanashia@gmail.com',
    linkedin: 'https://www.linkedin.com/in/manashi-pandey-56a427177',
    insta: 'https://www.instagram.com/as_smiling_face',
  },
  {
    name: 'Parth Patni',
    roles: 'Events-Head',
    url: 'https://picsum.photos/500',
    team: 'heads',
    email: 'parthpatni22@gmail.com',
    linkedin: 'https://www.linkedin.com/in/parth-patni-238063196',
    insta: ' https://www.instagram.com/parthpatni22',
  },
  {
    name: 'Jainil Vora',
    roles: 'Campaigning Head ',
    url: 'https://picsum.photos/500',
    team: 'heads',
    email: 'jainilvora1234@gmail.com',
    linkedin: 'https://www.linkedin.com/in/jainil-vora-094259128',
  },
  {
    name: 'Jainam Shah',
    roles: 'Sponsorship Head ',
    url: 'https://picsum.photos/500',
    team: 'heads',
    email: 'jainamshahldce@gmail.com',
    linkedin: 'https://www.linkedin.com/in/jainam-shah-6a6887193',
    insta: 'https://www.instagram.com/_jainam_shah_09',
  },
  {
    name: 'Om Raval',
    roles: 'Front-end',
    url: 'https://picsum.photos/500',
    team: 'core-team',
  },
  {
    name: 'Swati Panchal',
    roles: 'UI/UX',
    url: 'https://picsum.photos/500',
    team: 'core-team',
  },
  {
    name: 'Darshan Shah',
    roles: 'Back-end',
    url: 'https://picsum.photos/500',
    team: 'core-team',
  },
  {
    name: 'Nikita Tulsani',
    roles: 'Back-end',
    url: 'https://picsum.photos/500',
    team: 'core-team',
  },
  {
    name: 'Jainam Shah',
    roles: 'Management',
    url: 'https://picsum.photos/500',
    team: 'core-team',
  },
  {
    name: 'Neel Thakkar',
    roles: 'Back-end',
    url: 'https://picsum.photos/500',
    team: 'core-team',
  },
  {
    name: 'Vansh Prajapati',
    roles: 'Back-end',
    url: 'https://picsum.photos/500',
    team: 'core-team',
  },
  {
    name: 'Om Raval',
    roles: 'Front-end',
    url: 'https://picsum.photos/500',
    team: 'developers',
  },
  {
    name: 'Swati Panchal',
    roles: 'UI/UX',
    url: 'https://picsum.photos/500',
    team: 'developers',
  },
  {
    name: 'Darshan Shah',
    roles: 'Back-end',
    url: 'https://picsum.photos/500',
    team: 'developers',
  },
  {
    name: 'Nikita Tulsani',
    roles: 'Back-end',
    url: 'https://picsum.photos/500',
    team: 'developers',
  },
  {
    name: 'Jainam Shah',
    roles: 'Management',
    url: 'https://picsum.photos/500',
    team: 'developers',
  },
  {
    name: 'Neel Thakkar',
    roles: 'Back-end',
    url: 'https://picsum.photos/500',
    team: 'developers',
  },
  {
    name: 'Vansh Prajapati',
    roles: 'Back-end',
    url: 'https://picsum.photos/500',
    team: 'developers',
  },
];

export default Data;
