const Data = [
  {
    name: 'Kavisha Patel',
    roles: 'Events Convener',
    url: 'https://picsum.photos/500',
    team: 'convener',
    email: 'krpatel728@gmail.com',
    linkedin: 'https://www.linkedin.com/in/kavishapatel28072000',
    insta: 'https://www.instagram.com/kavisha_patel28/',
  },
  {
    name: 'Akash Bhat',
    roles: 'Events Convener',
    url: 'https://picsum.photos/500',
    team: 'convener',
    email: 'akashbhat0007@gmail.com',
    linkedin: 'https://www.linkedin.com/in/akash-bhat-5a234a163',
    insta: 'https://instagram.com/akash_bhat25?utm_medium=copy_link',
  },
  {
    name: 'Muskan Biala',
    roles: 'Marketing Convener',
    url: 'https://picsum.photos/500',
    team: 'convener',
    email: 'muskan.biala@gmail.com',
    linkedin: 'https://www.linkedin.com/in/muskan-biala-25898817a',
    insta: 'https://instagram.com/muskanbiala',
  },
  {
    name: 'Jinay Shah',
    roles: 'Campaigning Convener',
    url: 'https://picsum.photos/500',
    team: 'convener',
    email: 'jinayshah192@gmail.com ',
    linkedin: 'https://www.linkedin.com/in/jinay-shah-b7790518b',
    insta: 'https://instagram.com/15jinay?utm_medium=copy_link',
  },
  {
    name: 'Shivani Pandey',
    roles: 'Campaigning Convener',
    url: 'https://picsum.photos/500',
    team: 'convener',
    email: 'pandeyshivania@gmail.com',
    linkedin: 'https://www.linkedin.com/in/shivani-anand-pandey-59829a177',
    insta: 'https://www.instagram.com/she_as_vani',
  },
  {
    name: 'Utsav Doshi',
    roles: 'Events Convener',
    url: 'https://picsum.photos/500',
    team: 'convener',
    email: 'utsavdoshi321@gmail.com',
    linkedin: 'https://www.linkedin.com/in/utsav-doshi-058495196',
    insta: 'https://instagram.com/utsavdoshi_321?utm_medium=copy_link',
  },
  {
    name: 'Navneet Dubey',
    roles: 'Marketing Convener',
    url: 'https://picsum.photos/500',
    team: 'convener',
    email: 'navneetnkd123@gmail.com',
    linkedin: 'https://www.linkedin.com/in/navneet-dubey',
    insta: 'https://www.instagram.com/new_n_neat',
  },
  {
    name: 'Shubham Dave',
    roles: 'Campaigning Convener',
    url: 'https://picsum.photos/500',
    team: 'convener',
    email: 'daveshubham600@gmail.com',
    linkedin: 'https://www.linkedin.com/in/shubham-dave-b39494196',
    insta: 'https://instagram.com/dave_shubham_18?utm_medium=copy_link',
  },
  {
    name: 'Manashi Pandey',
    roles: 'Campaigning Convener',
    url: 'https://picsum.photos/500',
    team: 'convener',
    email: 'pandeymanashia@gmail.com',
    linkedin: 'https://www.linkedin.com/in/manashi-pandey-56a427177',
    insta: 'https://www.instagram.com/as_smiling_face',
  },
  {
    name: 'Parth Patni',
    roles: 'Events Head',
    url: 'https://picsum.photos/500',
    team: 'heads',
    email: 'parthpatni22@gmail.com',
    linkedin: 'https://www.linkedin.com/in/parth-patni-238063196',
    insta: ' https://www.instagram.com/parthpatni22',
  },
  {
    name: 'Jainil Vora',
    roles: 'Campaigning Head ',
    url: 'https://picsum.photos/500',
    team: 'heads',
    email: 'jainilvora1234@gmail.com',
    linkedin: 'https://www.linkedin.com/in/jainil-vora-094259128',
  },
  {
    name: 'Jainam Shah',
    roles: 'Sponsorship Head ',
    url: 'https://picsum.photos/500',
    team: 'heads',
    email: 'jainamshahldce@gmail.com',
    linkedin: 'https://www.linkedin.com/in/jainam-shah-6a6887193',
    insta: 'https://www.instagram.com/_jainam_shah_09',
  },
  {
    name: 'Om Raval',
    roles: 'Front-end Developer',
    url: 'https://picsum.photos/500',
    team: 'developers',
    email: 'r.auckwell18@gmail.com',
    insta: 'https://www.instagram.com/__omraval__/',
    linkedin: 'https://www.linkedin.com/in/om-raval-b56964167',
  },
  {
    name: 'Swati Panchal',
    roles: 'UI/UX Designer',
    url: 'https://picsum.photos/500',
    team: 'developers',
    linkedin: 'https://www.linkedin.com/in/swatipanchal23/',
    insta: 'https://instagram.com/uiuxeclectic?utm_medium=copy_link',
  },
  {
    name: 'Darshan Shah',
    roles: 'Front-End Developer',
    url: 'https://picsum.photos/500',
    team: 'developers',
    email: 'darshanshah7869@gmail.com',
    insta: 'https://www.instagram.com/darshan_shah7868',
    linkedin: 'https://www.linkedin.com/in/darshan-shah-b6b8671b4',
  },
  {
    name: 'Nikita Tulsani',
    roles: 'UI/UX Designer',
    url: 'https://picsum.photos/500',
    team: 'developers',
    email: 'nikita1312tulsani@gmail.com',
    insta: 'https://www.instagram.com/1312_nikita/',
    linkedin: 'https://www.linkedin.com/in/nikita-tulsani-128a551b0',
  },
  {
    name: 'Kaushik Prajapati',
    roles: 'Front-End Developer',
    url: 'https://picsum.photos/500',
    team: 'developers',
    insta: 'https://www.instagram.com/kaushikprajapati2002/',
    email: 'kaushikprajapati1970@gmail.com',
    linkedin: 'https://www.linkedin.com/in/kaushik-prajapati-396a331b3',
  },
  {
    name: 'Jay Prajapati',
    roles: 'Back-end Developer',
    url: 'https://picsum.photos/500',
    team: 'developers',
    insta: 'https://www.instagram.com/0jay_prajapati/',
    email: '1427jay@gmail.com',
    linkedin: 'https://www.linkedin.com/in/jay-prajapati-a01900204',
  },
  {
    name: 'Vansh Prajapati',
    roles: 'Back-end Developer',
    url: 'https://picsum.photos/500',
    team: 'developers',
    email: 'vanshj.prajapati@gmail.com',
    insta: 'https://instagram.com/vicky_thawne?utm_medium=copy_link',
    linkedin: 'https://www.linkedin.com/in/vansh-prajapati-3a683320b',
  },
  {
    name: 'Neel Thakkar',
    roles: 'Back-end Developer',
    url: 'https://picsum.photos/500',
    team: 'developers',
    email: 'neelthakkar2001@gmail.com',
    linkedin: 'https://www.linkedin.com/in/neel-thakkar-1221a0194/',
  },

  {
    name: 'khushvi purohit',
    email: 'khushvipurohit59@gmail.com',
    linkedin: 'https://www.linkedin.com/in/khushvi-purohit-7117b220b',
    roles: 'Core Team',
    team: 'core-team',
  },

  {
    name: 'Devanshi Soni',
    email: 'dvnshi.soni@gmail.com',
    linkedin: 'https://www.linkedin.com/in/devanshi-soni-543b37216',
    roles: 'Core Team',
    team: 'core-team',
  },
  {
    name: 'Anjali Jha',
    email: 'anjalijha291103@gmail.com ',
    linkedin: 'https://www.linkedin.com/in/anjali-jha-64693b20a',
    insta: ' https://www.instagram.com/_.anjali11',
    roles: 'Core Team',
    team: 'core-team',
  },
  {
    name: 'Harsh Patel',
    email: 'hhpatel1408@gmail.com',
    linkedin: 'https://www.linkedin.com/in/harsh-patel-190816216',
    roles: 'Core Team',
    team: 'core-team',
  },

  {
    name: 'Abinav k',
    email: 'abinavk02@gmail.com',
    linkedin: 'https://www.linkedin.com/in/abinav-k-155039173',
    roles: 'Core Team',
    team: 'core-team',
  },

  {
    name: 'Adarsh Mishra',
    email: 'adarsh289mishra@gmail.com',
    linkedin: 'https://www.linkedin.com/in/adarsh-mishra-23088a216',
    insta: 'https://www.instagram.com/adarsh.28/',
    roles: 'Core Team',
    team: 'core-team',
  },

  {
    name: 'Yug Patel',
    email: 'yugp1209@gmail.com',
    linkedin: 'https://www.linkedin.com/in/yug-patel-9571151ba',
    insta: 'https://www.instagram.com/yug_1209',
    roles: 'Core Team',
    team: 'core-team',
  },
  {
    name: 'Arpit Ojha',
    email: 'aptrockz@gmail.com',
    insta: 'https://www.instagram.com/_aptrockz_?r=nametag',
    roles: 'Core Team',
    team: 'core-team',
  },

  {
    name: 'Jeel Patel',
    linkedin: 'https://www.linkedin.com/in/jeel-patel-9394a21a6',
    Insta: 'https://www.instagram.com/__jeeeel/',
    email: ' jeel4580patel@gmail.com',
    roles: 'Core Team',
    team: 'core-team',
  },
];

export default Data;
